edition = "2024"
max_width = 100
tab_spaces = 4
newline_style= "Unix"
imports_granularity= "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
fn_single_line = false
where_single_line = false
trailing_comma = "Vertical"
trailing_semicolon = true
wrap_comments = true
comment_width = 100
normalize_comments = true
normalize_doc_attributes = true
format_strings = false
format_macro_matchers = true
use_field_init_shorthand = true
use_try_shorthand = true
condense_wildcard_suffixes = true